version: '3'
services:
        web:
                image: flask_open
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8303:8303"
                volumes:
                        - ./instance:/app/instance
                restart: unless-stopped
        socketio:
                image: socket_open
                build: ./socket
                ports:
                        - "8303:8303"
    
                restart: unless-stopped
